import importlib
import inspect
import sys
from pkgutil import iter_modules

from setuptools import find_packages


def find_modules(pkg, pkgpath):
    modules = set()
    if sys.version_info.major == 2 or (sys.version_info.major == 3 and sys.version_info.minor < 6):
        for _, name, ispkg in iter_modules([pkgpath]):
            if not ispkg:
                if pkg != "":
                    modules.add(pkg + '.' + name)
                else:
                    modules.add(name)
    else:
        for info in iter_modules([pkgpath]):
            if not info.ispkg:
                if pkg != "":
                    modules.add(pkg + '.' + info.name)
                else:
                    modules.add(info.name)
    return modules


def find_modules_in_packages(path):
    modules = find_modules("", path)
    for pkg in find_packages(path):
        modules.add(pkg)
        pkgpath = path + '/' + pkg.replace('.', '/')
        modules.update(find_modules(pkg, pkgpath))

    return modules


def is_class_or_method(value) -> bool:
    if inspect.isclass(value):
        return True
    if inspect.isfunction(value) and not inspect.isabstract(value) and not value.__name__.startswith("_"):
        return True
    return False


def generate_init():
    root_package = "visiongraph"
    module_blacklist = {"visiongraph.external", "visiongraph.tracker.motrackers"}
    module_with_methods = {"visiongraph.util"}
    import_blacklist = {"abstractmethod"}

    modules = find_modules_in_packages(root_package)

    lines = []

    for module in modules:
        pgk_path = f"{root_package}.{module}"

        filter_method = inspect.isclass

        if any([pgk_path.startswith(e) for e in module_blacklist]):
            continue

        if any([pgk_path.startswith(e) for e in module_with_methods]):
            filter_method = is_class_or_method

        for name, cls in inspect.getmembers(importlib.import_module(pgk_path), filter_method):
            if inspect.isclass(cls) and cls.__module__ != pgk_path:
                continue

            if name in import_blacklist:
                continue

            line = f"from .{module} import {name}"
            lines.append(line)

    # lines = sorted(lines)

    # append header and empty line
    lines.insert(0, "# This file has been auto-generated by generate_init.py.")
    lines.append("")

    with open(f"{root_package}/__init__.py", "w+") as file:
        file.write("\n".join(lines))


if __name__ == "__main__":
    print("generating init.py ...")
    generate_init()
    print("done")
