import ast
import distutils.cmd
import glob
import os
from pathlib import Path
from sys import platform
from typing import Set
from typing import Tuple, List

from setuptools import find_packages
from setuptools import setup


class GenerateInitPy(distutils.cmd.Command):
    description = 'generate top-level init py'
    user_options = []

    root_package = "visiongraph"

    excluded_modules = {
        "visiongraph.external",
        "visiongraph.tracker.motrackers"
    }

    late_import_modules = {
        "visiongraph.estimator.openvino.OpenVinoPoseEstimator"
    }

    optional_modules = {
        "pyrealsense2",
        "pyk4a",
        "openvino",
        "mediapipe",
        "onnxruntime",
        "moviepy"
    }

    module_with_methods = {
        "visiongraph.util"
    }

    @staticmethod
    def get_files_in_path(path: str, extensions: [str] = ["*.*"]) -> [str]:
        return sorted([f for ext in extensions for f in glob.glob(os.path.join(path, ext), recursive=True)])

    def analyse_source_file(self, file_path: str) -> List[Tuple[str, str, bool]]:
        """
        Finds all class definitions in the source files and imports them.
        :param file_path: Path to the python source file.
        :return: List of imported modules / names and if they should be optional.
        """
        with open(file_path, "r") as file:
            source = file.read()

        results: List[Tuple[str, str, bool]] = []

        module = file_path.replace("/", ".").replace("\\", ".").replace(".py", "")
        optional = False

        # skip if is excluded
        if any([module.startswith(e) for e in self.excluded_modules]):
            return results

        nodes = ast.parse(source)
        for node in ast.iter_child_nodes(nodes):
            # classes
            if isinstance(node, ast.ClassDef):
                results.append((module, node.name, optional))

            # imports to check if is optional module
            elif isinstance(node, ast.Import):
                for import_name in node.names:
                    if any([import_name.name.startswith(e) for e in self.optional_modules]):
                        optional = True

            elif isinstance(node, ast.ImportFrom):
                if any([node.module.startswith(e) for e in self.optional_modules]):
                    optional = True

            # methods for modules that should be included
            elif isinstance(node, ast.FunctionDef):
                if any([module.startswith(e) for e in self.module_with_methods]):
                    results.append((module, node.name, optional))

        return results

    def run(self) -> None:
        # analyse source files
        source_files = self.get_files_in_path(f"{self.root_package}/**", ["*.py"])
        imports = [self.analyse_source_file(f) for f in source_files]
        imports = [i for sl in imports for i in sl]

        # re-order-late imports
        late_imports = [i for i in imports if any([i[0].startswith(e) for e in self.late_import_modules])]
        for li in late_imports:
            imports.remove(li)
            imports.append(li)

        # generate python code
        lines = []
        for module, name, optional in imports:
            # relative import
            module = module.replace(self.root_package, "")
            import_line = f"from {module} import {name}"

            if optional:
                line = f"try:\n    {import_line}\nexcept ModuleNotFoundError as ex:\n    " \
                       f"logging.debug(f\"Could not import {name}\")"
                lines.append(line)
            else:
                lines.append(import_line)

        # append header, imports and empty line at the end
        lines.insert(0, "# This file has been auto-generated by generate_init.py.")
        lines.insert(1, "import logging")
        lines.append("")

        with open(f"{self.root_package}/__init__.py", "w+") as file:
            file.write("\n".join(lines))

    def initialize_options(self) -> None:
        pass

    def finalize_options(self) -> None:
        pass


# define required packages
required_packages = find_packages(exclude=["tests", "examples"])

BASE_NAME = "__required__"
ALL_NAME = "all"


def parse_requirements():
    extras = {}

    with open('requirements.txt') as f:
        lines = f.read().splitlines()

    extra_name = BASE_NAME
    extra_items: List[str] = []

    os_dependent: Set[str] = set()

    skip_extra = False
    for line in [line.strip() for line in lines if line != ""]:
        if line.startswith("# extra"):
            # add current extra
            if not skip_extra:
                extras[extra_name] = extra_items
            else:
                skip_extra = False

            # prepare new extra
            extra_items: List[str] = []

            tokens = line.split(" ")
            extra_name = tokens[2]

            if len(tokens) > 3:
                os_dependent.add(extra_name)
                os_names = tokens[3].split(",")
                if not any([platform.startswith(os_name) for os_name in os_names]):
                    # os not supporting this dependency
                    print(f"Setup: Skipping extra {extra_name} because it is not support on {platform}.")
                    skip_extra = True
                    continue

        elif line.startswith("#"):
            continue
        elif line.startswith("-"):
            continue
        else:
            extra_items.append(line)

    # add last group
    extras[extra_name] = extra_items

    # extract base packages
    install = extras.pop(BASE_NAME)

    # create all group
    all_reqs = [v for k, v in extras.items() if k not in os_dependent]
    extras[ALL_NAME] = []
    for reqs in all_reqs:
        extras[ALL_NAME] += reqs

    return install, extras


install_required, extras_required = parse_requirements()

# read readme
current_dir = Path(__file__).parent
long_description = (current_dir / "README.md").read_text()

setup(
    name="visiongraph",
    version='0.1.10',
    packages=required_packages,
    url='https://github.com/cansik/visiongraph',
    license='MIT License',
    author='Florian Bruggisser',
    author_email='github@broox.ch',
    description='Visiongraph is a high level computer vision pipeline.',
    long_description=long_description,
    long_description_content_type="text/markdown",
    install_requires=install_required,
    extras_require=extras_required,
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers',
        'Intended Audience :: Education',
        'Intended Audience :: Science/Research',
        'License :: OSI Approved :: MIT License',
        'Operating System :: MacOS :: MacOS X',
        'Operating System :: Microsoft :: Windows',
        'Operating System :: POSIX :: Linux',
        'Programming Language :: Python :: 3 :: Only',
        'Topic :: Scientific/Engineering',
        'Topic :: Scientific/Engineering :: Image Processing',
        'Topic :: Scientific/Engineering :: Artificial Intelligence',
        'Topic :: Software Development',
        'Topic :: Software Development :: Libraries',
        'Topic :: Software Development :: Libraries :: Python Modules',
    ],
    cmdclass={
        'generate_init': GenerateInitPy,
    },
)
