import distutils.cmd
import importlib
import inspect
import sys
from pathlib import Path
from pkgutil import iter_modules
from sys import platform
from typing import List, Set

from setuptools import find_packages
from setuptools import setup


class GenerateInitPy(distutils.cmd.Command):
    root_package = "visiongraph"

    module_blacklist = {
        "visiongraph.external",
        "visiongraph.tracker.motrackers"
    }

    optional_modules = {
        "pyrealsense2",
        "pyk4a",
        "openvino",
        "mediapipe",
        "onnxruntime",
        "moviepy"
    }

    module_with_methods = {
        "visiongraph.util"
    }

    import_blacklist = {
        "abstractmethod"
    }

    description = 'generate top-level init py'
    user_options = []

    @staticmethod
    def find_modules(pkg, pkgpath):
        modules = set()
        if sys.version_info.major == 2 or (sys.version_info.major == 3 and sys.version_info.minor < 6):
            for _, name, ispkg in iter_modules([pkgpath]):
                if not ispkg:
                    if pkg != "":
                        modules.add(pkg + '.' + name)
                    else:
                        modules.add(name)
        else:
            for info in iter_modules([pkgpath]):
                if not info.ispkg:
                    if pkg != "":
                        modules.add(pkg + '.' + info.name)
                    else:
                        modules.add(info.name)
        return modules

    @staticmethod
    def find_modules_in_packages(path):
        modules = GenerateInitPy.find_modules("", path)
        for pkg in find_packages(path):
            modules.add(pkg)
            pkgpath = path + '/' + pkg.replace('.', '/')
            modules.update(GenerateInitPy.find_modules(pkg, pkgpath))

        return modules

    @staticmethod
    def is_class_or_method(value) -> bool:
        if inspect.isclass(value):
            return True
        if inspect.isfunction(value) and not inspect.isabstract(value) and not value.__name__.startswith("_"):
            return True
        return False

    def initialize_options(self) -> None:
        pass

    def run(self) -> None:
        modules = self.find_modules_in_packages(self.root_package)
        optional_packages = set()

        imports = []
        for module in modules:
            pgk_path = f"{self.root_package}.{module}"

            filter_method = inspect.isclass

            if any([pgk_path.startswith(e) for e in self.module_blacklist]):
                continue

            if any([pgk_path.startswith(e) for e in self.module_with_methods]):
                filter_method = self.is_class_or_method

            for name, cls in inspect.getmembers(importlib.import_module(pgk_path)):
                if inspect.ismodule(cls) and any([cls.__name__.startswith(e) for e in self.optional_modules]):
                    optional_packages.add(pgk_path)

                if inspect.isclass(cls) and any([cls.__module__.startswith(e)
                                                 for e in self.optional_modules]):
                    optional_packages.add(pgk_path)

                if inspect.isclass(cls) and cls.__module__ != pgk_path:
                    continue

                if name in self.import_blacklist:
                    continue

                if not filter_method(cls):
                    continue

                imports.append((module, name))

        # generate python code
        lines = []
        for module, name in imports:
            import_line = f"from .{module} import {name}"

            if f"{self.root_package}.{module}" in optional_packages:
                line = f"""try:
    {import_line}
except ModuleNotFoundError as ex:
    logging.debug(f"Could not import {name}")"""

                lines.append(line)
            else:
                lines.append(import_line)

        # append header, imports and empty line at the end
        lines.insert(0, "# This file has been auto-generated by generate_init.py.")
        lines.insert(1, "import logging")
        lines.append("")

        with open(f"{self.root_package}/__init__.py", "w+") as file:
            file.write("\n".join(lines))

    def finalize_options(self) -> None:
        pass


# define required packages
required_packages = find_packages(exclude=["tests", "examples"])

BASE_NAME = "__required__"
ALL_NAME = "all"


def parse_requirements():
    extras = {}

    with open('requirements.txt') as f:
        lines = f.read().splitlines()

    extra_name = BASE_NAME
    extra_items: List[str] = []

    os_dependent: Set[str] = set()

    skip_extra = False
    for line in [line.strip() for line in lines if line != ""]:
        if line.startswith("# extra"):
            # add current extra
            if not skip_extra:
                extras[extra_name] = extra_items
            else:
                skip_extra = False

            # prepare new extra
            extra_items: List[str] = []

            tokens = line.split(" ")
            extra_name = tokens[2]

            if len(tokens) > 3:
                os_dependent.add(extra_name)
                os_names = tokens[3].split(",")
                if not any([platform.startswith(os_name) for os_name in os_names]):
                    # os not supporting this dependency
                    print(f"Setup: Skipping extra {extra_name} because it is not support on {platform}.")
                    skip_extra = True
                    continue

        elif line.startswith("#"):
            continue
        elif line.startswith("-"):
            continue
        else:
            extra_items.append(line)

    # add last group
    extras[extra_name] = extra_items

    # extract base packages
    install = extras.pop(BASE_NAME)

    # create all group
    all_reqs = [v for k, v in extras.items() if k not in os_dependent]
    extras[ALL_NAME] = []
    for reqs in all_reqs:
        extras[ALL_NAME] += reqs

    return install, extras


install_required, extras_required = parse_requirements()

# read readme
current_dir = Path(__file__).parent
long_description = (current_dir / "README.md").read_text()

setup(
    name="visiongraph",
    version='0.1.10',
    packages=required_packages,
    url='https://github.com/cansik/visiongraph',
    license='MIT License',
    author='Florian Bruggisser',
    author_email='github@broox.ch',
    description='Visiongraph is a high level computer vision pipeline.',
    long_description=long_description,
    long_description_content_type="text/markdown",
    install_requires=install_required,
    extras_require=extras_required,
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers',
        'Intended Audience :: Education',
        'Intended Audience :: Science/Research',
        'License :: OSI Approved :: MIT License',
        'Operating System :: MacOS :: MacOS X',
        'Operating System :: Microsoft :: Windows',
        'Operating System :: POSIX :: Linux',
        'Programming Language :: Python :: 3 :: Only',
        'Topic :: Scientific/Engineering',
        'Topic :: Scientific/Engineering :: Image Processing',
        'Topic :: Scientific/Engineering :: Artificial Intelligence',
        'Topic :: Software Development',
        'Topic :: Software Development :: Libraries',
        'Topic :: Software Development :: Libraries :: Python Modules',
    ],
    cmdclass={
        'generate_init': GenerateInitPy,
    },
)
