# This file has been auto-generated by generate_init.py.
import logging
from .input.VideoCaptureInput import VideoCaptureInput
from .estimator.spatial.SSDDetector import SSDConfig
from .estimator.spatial.SSDDetector import SSDDetector
from .result.spatial.pose.PoseLandmarkResult import PoseLandmarkResult
from .estimator.spatial.LandmarkEstimator import LandmarkEstimator
from .result.DepthMap import DepthMap
from .Pipeline import Pipeline
from .estimator.translation.DepthEstimator import DepthEstimator
from .data.RepositoryAsset import RepositoryAsset
from .result.spatial.SpatialCascadeResult import SpatialCascadeResult
try:
    from .result.spatial.pose.BlazePose import BlazePose
except ModuleNotFoundError as ex:
    logging.debug(f"Could not import BlazePose")
from .estimator.spatial.face.landmark.RegressionLandmarkEstimator import RegressionLandmarkEstimator
from .estimator.spatial.face.OpenVinoFaceDetector import OpenVinoFaceConfig
from .estimator.spatial.face.OpenVinoFaceDetector import OpenVinoFaceDetector
from .util.NetworkUtils import download_file
from .util.NetworkUtils import prepare_data_file
from .util.NetworkUtils import prepare_openvino_model
from .util.CollectionUtils import default_value_dict
from .estimator.spatial.pose.OpenPoseEstimator import OpenPoseConfig
from .estimator.spatial.pose.OpenPoseEstimator import OpenPoseEstimator
from .result.spatial.hand.HandLandmarkResult import HandLandmarkResult
try:
    from .estimator.openvino.OpenVinoObjectDetector import OpenVinoObjectDetector
except ModuleNotFoundError as ex:
    logging.debug(f"Could not import OpenVinoObjectDetector")
from .input.BaseDepthInput import BaseDepthInput
from .estimator.spatial.face.pose.HeadPoseEstimator import HeadPoseEstimator
from .model.types.RealSenseColorScheme import RealSenseColorScheme
from .result.spatial.face.RegressionFace import RegressionFace
from .util.LoggingUtils import add_logging_parameter
from .util.LoggingUtils import setup_logging
from .util.ArgUtils import PipelineNodeFactory
from .util.ArgUtils import add_dict_choice_argument
from .util.ArgUtils import add_enum_choice_argument
from .util.ArgUtils import add_step_choice_argument
from .util.ArgUtils import dict_choice
from .util.ArgUtils import float_range
from .data.LocalAsset import LocalAsset
from .estimator.spatial.face.pose.AdasHeadPoseEstimator import AdasHeadPoseEstimator
from .estimator.spatial.hand.landmark.HandLandmarkEstimator import HandLandmarkEstimator
from .data.Asset import Asset
from .signal.OneEuroFilter import OneEuroFilter
from .estimator.VisionClassifier import VisionClassifier
from .VisionGraph import VisionGraph
from .estimator.ScoreThresholdEstimator import ScoreThresholdEstimator
from .estimator.spatial.RoiEstimator import RoiEstimator
try:
    from .recorder.MoviePyVideoRecorder import MoviePyVideoRecorder
except ModuleNotFoundError as ex:
    logging.debug(f"Could not import MoviePyVideoRecorder")
from .recorder.BaseFrameRecorder import BaseFrameRecorder
from .estimator.spatial.pose.MoveNetPoseEstimator import MoveNetConfig
from .estimator.spatial.pose.MoveNetPoseEstimator import MoveNetPoseEstimator
try:
    from .result.spatial.hand.BlazeHand import BlazeHand
except ModuleNotFoundError as ex:
    logging.debug(f"Could not import BlazeHand")
try:
    from .input.RealSenseInput import RealSenseInput
except ModuleNotFoundError as ex:
    logging.debug(f"Could not import RealSenseInput")
try:
    from .input.AzureKinectInput import AzureKinectInput
except ModuleNotFoundError as ex:
    logging.debug(f"Could not import AzureKinectInput")
from .recorder.FrameSetRecorder import FrameSetRecorder
from .util.ResultUtils import list_of_vector4D
from .util.ResultUtils import non_maximum_suppression
from .estimator.ChainEstimator import ChainEstimator
from .util.MathUtils import StreamingMovingAverage
from .util.MathUtils import constrain
from .util.MathUtils import map_value
from .util.MathUtils import rotate_2d
from .util.MathUtils import transform_coordinates
from .model.parameter.ArgumentConfigurable import ArgumentConfigurable
from .result.spatial.LandmarkDetectionResult import LandmarkDetectionResult
try:
    from .estimator.spatial.pose.MediaPipePoseEstimator import MediaPipePoseEstimator
except ModuleNotFoundError as ex:
    logging.debug(f"Could not import MediaPipePoseEstimator")
try:
    from .estimator.spatial.pose.MediaPipePoseEstimator import PoseModelComplexity
except ModuleNotFoundError as ex:
    logging.debug(f"Could not import PoseModelComplexity")
try:
    from .estimator.translation.MidasDepthEstimator import MidasConfig
except ModuleNotFoundError as ex:
    logging.debug(f"Could not import MidasConfig")
try:
    from .estimator.translation.MidasDepthEstimator import MidasDepthEstimator
except ModuleNotFoundError as ex:
    logging.debug(f"Could not import MidasDepthEstimator")
from .result.BaseResult import BaseResult
from .estimator.spatial.YOLODetector import YOLOArchitecture
from .estimator.spatial.YOLODetector import YOLOConfig
from .estimator.spatial.YOLODetector import YOLODetector
from .recorder.CV2VideoRecorder import CV2VideoRecorder
from .result.ClassificationResult import ClassificationResult
from .PipelineNode import PipelineNode
from .estimator.spatial.hand.HandDetector import FaceDetector
from .estimator.spatial.ObjectDetector import ObjectDetector
from .model.chain.ChainableNode import ChainableNode
from .result.spatial.ObjectDetectionResult import ObjectDetectionResult
from .result.HeadPoseResult import HeadPoseResult
from .result.ImageResult import ImageResult
try:
    from .estimator.spatial.hand.landmark.MediaPipeHandEstimator import HandModelComplexity
except ModuleNotFoundError as ex:
    logging.debug(f"Could not import HandModelComplexity")
try:
    from .estimator.spatial.hand.landmark.MediaPipeHandEstimator import MediaPipeHandEstimator
except ModuleNotFoundError as ex:
    logging.debug(f"Could not import MediaPipeHandEstimator")
try:
    from .estimator.spatial.face.MediaPipeFaceDetector import MediaPipeFaceDetector
except ModuleNotFoundError as ex:
    logging.debug(f"Could not import MediaPipeFaceDetector")
try:
    from .estimator.spatial.face.MediaPipeFaceDetector import MediaPipeFaceModel
except ModuleNotFoundError as ex:
    logging.debug(f"Could not import MediaPipeFaceModel")
from .result.spatial.hand.Handedness import Handedness
from .util.DrawingUtils import draw_axis
from .util.DrawingUtils import draw_bbox
from .result.spatial.hand.HandDetectionResult import HandDetectionResult
from .estimator.spatial.face.landmark.FaceLandmarkEstimator import FaceLandmarkEstimator
from .estimator.spatial.face.AdasFaceDetector import AdasFaceConfig
from .estimator.spatial.face.AdasFaceDetector import AdasFaceDetector
from .recorder.AsyncFrameSetRecorder import AsyncFrameSetRecorder
from .model.geometry.BoundingBox2D import BoundingBox2D
from .model.tracker.Trackable import Trackable
from .tracker.ObjectDetectionTracker import ObjectDetectionTracker
from .util.TimeUtils import FPSTracer
from .util.TimeUtils import ProfileWatch
from .util.TimeUtils import Watch
from .util.TimeUtils import current_millis
try:
    from .estimator.openvino.OpenVinoPoseEstimator import OpenVinoPoseEstimator
except ModuleNotFoundError as ex:
    logging.debug(f"Could not import OpenVinoPoseEstimator")
from .result.spatial.face.FaceLandmarkResult import FaceLandmarkResult
try:
    from .estimator.openvino.VisionInferenceEngine import VisionInferenceEngine
except ModuleNotFoundError as ex:
    logging.debug(f"Could not import VisionInferenceEngine")
from .estimator.spatial.pose.PoseEstimator import PoseEstimator
from .estimator.spatial.face.FaceDetector import FaceDetector
from .result.spatial.face.BlazeFace import BlazeFace
from .estimator.BaseEstimator import BaseEstimator
from .estimator.VisionEstimator import VisionEstimator
from .input.BaseInput import BaseInput
from .estimator.spatial.SpatialCascadeEstimator import SpatialCascadeEstimator
from .estimator.spatial.pose.AEPoseEstimator import AEPoseConfig
from .estimator.spatial.pose.AEPoseEstimator import AEPoseEstimator
from .result.spatial.face.FaceDetectionResult import FaceDetectionResult
from .result.spatial.pose.COCOPose import COCOPose
try:
    from .estimator.openvino.SyncInferencePipeline import SyncInferencePipeline
except ModuleNotFoundError as ex:
    logging.debug(f"Could not import SyncInferencePipeline")
from .model.DepthBuffer import DepthBuffer
from .util.ImageUtils import constrain
from .util.ImageUtils import extract_roi_safe
from .util.ImageUtils import resize_and_letter_box
from .estimator.BaseClassifier import BaseClassifier
