name: Visiongraph Test

on:
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: windows
            host: windows-latest
            args:

          - name: macos-silicon
            host: macos-latest
            args:

          - name: ubuntu
            host: ubuntu-latest
            args:
        python-version: [ '3.10', '3.11' ]

    runs-on: ${{ matrix.os.host }}

    name: python ${{ matrix.python-version }} on ${{ matrix.os.host }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # install os specific
      - name: Install ffmpeg
        if: runner.os == 'macOS'
        run: |
          brew install ffmpeg

      # install pip packages
      - name: Install visiongraph
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          pip install uv "huggingface_hub[cli]"
          uv sync --all-extras --dev

      - name: "Download all models from Hugging Face"
        shell: bash
        env:
          HF_TOKEN: ${{ secrets.HF_HUB_TOKEN }}
        run: |
          cd $GITHUB_WORKSPACE
          python - << 'EOF'
          from huggingface_hub import snapshot_download
          # Pulls entire repo snapshot into visiongraph/cache
          snapshot_download(
              repo_id="cansik/visiongraph",
              local_dir="visiongraph/cache",
              token="${HF_HUB_TOKEN}"
          )
          EOF

      # check networks
      - name: Check networks
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          ls -la visiongraph/cache

      # run test
      - name: Test visiongraph
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          uv run python -m unittest discover -s ./tests -t ./ -v