name: Visiongraph Test

on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest' ]
        python-version: [ '3.7', '3.8', '3.9' ]

    runs-on: ${{ matrix.os }}

    name: python ${{ matrix.python-version }} on ${{ matrix.os }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # install pip packages
      - name: Install visiongraph
        run: pip install visiongraph[all] --use-deprecated=legacy-resolver

      # run test
      - name: Test visiongraph
        run: |
          cd $GITHUB_WORKSPACE
          python tests/ImportTest.py